import 'package:finwise/core/widgets/loader.dart';
import 'package:finwise/features/bottom_nav_bar/presentation/view/app_bottom_nav_bar.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';

import '../../../../core/constant/app_colors.dart';
import '../../../../core/widgets/form_input.dart';
import '../../../login/presentation/view/login_screen.dart';
import '../../domain/entities/user_entity.dart';
import '../riverpod/sign_up_controller.dart';

class SignupScreen extends ConsumerStatefulWidget {
  const SignupScreen({super.key});

  @override
  ConsumerState<SignupScreen> createState() => _SignupScreenState();
}

class _SignupScreenState extends ConsumerState<SignupScreen> {
  // Controllers for form fields
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _mobileController = TextEditingController();
  final _dobController = TextEditingController();
  final _passwordController = TextEditingController();
  final _confirmPasswordController = TextEditingController();
  final _formKey = GlobalKey<FormState>();
  bool _showPassword = false;
  bool _showConfirmPassword = false;
  DateTime? _selectedDate;

  @override
  void dispose() {
    _nameController.dispose();
    _emailController.dispose();
    _mobileController.dispose();
    _dobController.dispose();
    _passwordController.dispose();
    _confirmPasswordController.dispose();
    super.dispose();
  }

  // Date picker helper for FinWise users
  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime(2000),
      firstDate: DateTime(1920),
      lastDate: DateTime.now(),
    );
    if (picked != null) {
      setState(() {
        _selectedDate = picked;
        _dobController.text = DateFormat('dd/MM/yyyy').format(picked);
      });
    }
  }

  void _onSignUpPressed() {
    if (_passwordController.text != _confirmPasswordController.text) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text("Passwords do not match!")));
      return;
    }

    final user = UserEntity(
      userId: '', // Generated by Firebase
      fullName: _nameController.text.trim(),
      email: _emailController.text.trim(),
      mobileNumber: _mobileController.text.trim(),
      dateOfBirth: _selectedDate ?? DateTime.now(),
    );

    ref
        .read(signUpControllerProvider.notifier)
        .signUp(password: _passwordController.text.trim(), user: user);
  }

  @override
  Widget build(BuildContext context) {
    // Listen for state changes to show errors or navigate
    ref.listen<AsyncValue<UserEntity?>>(signUpControllerProvider, (
      previous,
      next,
    ) {
      next.whenOrNull(
        error: (error, stack) => ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text(error.toString()))),
        data: (user) {
          if (user != null) {
            //clear form state
            _formKey.currentState?.reset();
            // Navigate to Login screen
            Navigator.pushAndRemoveUntil(
              context,
              MaterialPageRoute(builder: (_) => AppBottomNavBar()),
              (path) => false,
            );
          }
        },
      );
    });

    final signUpState = ref.watch(signUpControllerProvider);

    return Scaffold(
      body: Column(
        children: [
          Expanded(
            flex: 3,
            child: SafeArea(
              child: Center(
                child: SizedBox(
                  width: 300,
                  child: Text(
                    'Create account',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      fontSize: 30,
                      fontWeight: FontWeight.w700,
                      color: AppColors.cyprusGreen,
                    ),
                  ),
                ),
              ),
            ),
          ),
          Expanded(
            flex: 10,
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 40),
              clipBehavior: Clip.hardEdge,
              decoration: BoxDecoration(
                color: AppColors.honeydewGreen,
                borderRadius: const BorderRadius.only(
                  topLeft: Radius.circular(50),
                  topRight: Radius.circular(50),
                ),
              ),
              child: SingleChildScrollView(
                child: Form(
                  key: _formKey,
                  child: Column(
                    children: [
                      const SizedBox(height: 50),
                      FormInput(
                        controller: _nameController,
                        hintText: "John Doe",
                        labelText: "Full Name",
                      ),
                      const SizedBox(height: 10),
                      FormInput(
                        controller: _emailController,
                        hintText: "example@gmail.com",
                        labelText: "Email",
                      ),
                      const SizedBox(height: 10),
                      FormInput(
                        controller: _mobileController,
                        hintText: "+880 1434-567890",
                        labelText: "Mobile Number",
                        keyboardType: TextInputType.number,
                      ),
                      const SizedBox(height: 10),
                      GestureDetector(
                        onTap: () => _selectDate(context),
                        child: AbsorbPointer(
                          child: FormInput(
                            controller: _dobController,
                            hintText: "DD/MM/YYYY",
                            labelText: "Date of Birth",
                          ),
                        ),
                      ),
                      const SizedBox(height: 10),
                      FormInput(
                        controller: _passwordController,
                        labelText: 'Password',
                        hintText: "● ● ● ● ● ● ● ●",
                        obscureText: !_showPassword,
                        suffixIcon: GestureDetector(
                          onTap: () {
                            setState(() {
                              _showPassword = !_showPassword;
                            });
                          },
                          child: Icon(
                            _showPassword ? Icons.lock_open : Icons.lock,
                            color: AppColors.textGreenColor,
                          ),
                        ),
                      ),
                      const SizedBox(height: 10),
                      FormInput(
                        controller: _confirmPasswordController,
                        labelText: 'Confirm Password',
                        hintText: "● ● ● ● ● ● ● ●",
                        obscureText: !_showConfirmPassword,
                        suffixIcon: GestureDetector(
                          onTap: () {
                            setState(() {
                              _showConfirmPassword = !_showConfirmPassword;
                            });
                          },
                          child: Icon(
                            _showConfirmPassword ? Icons.lock_open : Icons.lock,
                            color: AppColors.textGreenColor,
                          ),
                        ),
                      ),
                      const SizedBox(height: 10),

                      // Terms and Conditions Section
                      _buildTermsText(),

                      const SizedBox(height: 10),

                      // Submit Button with Loading State
                      signUpState.isLoading
                          ? Loader()
                          : ElevatedButton(
                              onPressed: () {
                                if (_formKey.currentState?.validate() ??
                                    false) {
                                  _onSignUpPressed();
                                }
                              },
                              child: Text(
                                'Sign Up',
                                style: TextStyle(
                                  color: AppColors.textGreenColor,
                                  fontWeight: FontWeight.w700,
                                  fontSize: 20,
                                ),
                              ),
                            ),

                      const SizedBox(height: 10),

                      _buildLoginRedirect(context),
                      const SizedBox(height: 20),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTermsText() {
    return TextButton(
      onPressed: () {},
      child: RichText(
        textAlign: TextAlign.center,
        text: TextSpan(
          text: 'By continuing, you agree to',
          style: TextStyle(
            color: const Color(0xff4B4544),
            fontFamily: GoogleFonts.leagueSpartan().fontFamily,
            fontSize: 14,
          ),
          children: const [
            TextSpan(
              text: ' Terms of Use',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            TextSpan(text: ' and'),
            TextSpan(
              text: ' Privacy Policy.',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLoginRedirect(BuildContext context) {
    return TextButton(
      onPressed: () => Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (context) => const LoginScreen()),
      ),
      child: RichText(
        text: TextSpan(
          text: 'Already have an account? ',
          style: TextStyle(
            fontFamily: GoogleFonts.leagueSpartan().fontFamily,
            color: AppColors.textGreenColor,
            fontSize: 13,
          ),
          children: [
            TextSpan(
              text: 'Log In',
              style: TextStyle(color: AppColors.vividBlue),
            ),
          ],
        ),
      ),
    );
  }
}
